### ISSUE TITLE
"Google Cloud Storage" toolwindow icon is larger than other toolwindow icons

### ISSUE THREAD

**Issue by yole** [GoogleCloudPlatform/cloud-code-intellij#2204]
(Please ensure you are running the latest version of Cloud Tools for IntelliJ with _Help > Check for Updates_.)

- Cloud Tools for IntelliJ version: 18.6.1
- Google Cloud SDK version _(run `gcloud version` on the command line)_: doesn't matter
- OS: Mac OS

**What did you do?**

Started the IDE with the plugin installed.

**What did you expect to see?**

A toolwindow icon that is the same size as other toolwindow icons (13x13)

**What did you see instead?**

A large icon (16x16).

(screenshots are helpful)

**Comment by etanshaul** [comment]
thanks @yole. what version of IDEA did you notice this on. on 2018.1 on both a high dpi and regular screens it seems ok (shown below on high dpi):

<img width="48" alt="screen shot 2018-06-28 at 11 11 57 am" src="https://user-images.githubusercontent.com/1735744/42043343-3849bfd6-7ac4-11e8-8d81-7c7649d7042a.png">

**Comment by yole** [comment]
I'm using 2018.2 beta.

**Comment by etanshaul** [comment]
fixed. out in the next release.

**Comment by ivanporty** [comment]
Still seeing a warning on the icon, the preferred size is 13x13px.

**Comment by jmah-cc** [comment]
This will be in the next release.
